require: rubocop-performance
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
    - 'example/**/*'
Layout/LineLength:
  Max: 120
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/FloatComparison:
  Exclude:
    - spec/app/models/version_spec.rb
Lint/MissingSuper:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Lint/UselessMethodDefinition:
  Exclude:
    - spec/lib/finders/same_type_finder_spec.rb
    - spec/lib/finders/unique_finder_spec.rb
Metrics/AbcSize:
  Max: 28
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 18
  Exclude:
    - app/controllers/core/cli_options.rb
Metrics/ParameterLists:
  Max: 6
  MaxOptionalParameters: 4
Metrics/PerceivedComplexity:
  Max: 9
Style/ClassVars:
  Enabled: false
Style/CombinableLoops:
  Exclude:
    - spec/lib/controllers_spec.rb
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Exclude:
    - lib/cms_scanner/finders/finder.rb
Style/MixinUsage:
  Exclude:
    - lib/cms_scanner/formatter.rb
